
[env:WLED_COMPILE]
extends = env:esp32s3dev_16MB_opi

build_flags = ${common.build_flags} ${esp32s3.build_flags} -D WLED_RELEASE_NAME=\"ESP32-S3_16MB_opi\"
  -D WLED_WATCHDOG_TIMEOUT=0
  ;-D ARDUINO_USB_CDC_ON_BOOT=0  ;; -D ARDUINO_USB_MODE=1 ;; for boards with serial-to-USB chip
  -D ARDUINO_USB_CDC_ON_BOOT=1 ;; -D ARDUINO_USB_MODE=1      ;; for boards with USB-OTG connector only (USBCDC or "TinyUSB")
  -DBOARD_HAS_PSRAM
  -D CLIENT_SSID='"WLAN"'
  -D CLIENT_PASS='"PASSWRD"'

custom_usermods = multiple_rotary_encoder

lib_deps = ${esp32s3.lib_deps}
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library