#pragma once
#include <Arduino.h>
#include <Wire.h>
// #include <Adafruit_GFX.h>
// #include <Adafruit_SSD1306.h>
#include <U8g2lib.h>
#include <SPI.h>
#include "encoderTypes.h" // Needs to know the modes to draw them!

// #define SCREEN_WIDTH 128
// #define SCREEN_HEIGHT 64
// #define OLED_RESET -1


#define SPI_CLK   18   // GPIO 18 - SPI Clock
#define SPI_MOSI  23   // GPIO 23 - SPI Data (Master Out Slave In)
#define SPI_MISO  19   // GPIO 19 - SPI Data (Master In Slave Out) - not needed for display
#define OLED_CS   5    // GPIO 5  - Chip Select
#define OLED_DC   4    // GPIO 4  - Data/Command
#define OLED_RST  6    // GPIO 6  - Reset

#define Serial Serial0

// Generated by Advanced Image2C++ Converter
// Display: SSD1306 (64x32)
// Format: 1-bit Monochrome
// Inverted: Yes
// Dithering: Yes
// Rotation: 0°
// Background: #fdfcfc

const uint8_t BrightnessSymbol[] PROGMEM = {
  0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b10000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000001, 0b10000000, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b00000001, 0b10000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000001, 0b10000000, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000011, 0b00000001, 0b10000000, 0b11000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000011, 0b10000001, 0b10000001, 0b11000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000001, 0b11000000, 0b00000011, 0b10000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b11100000, 0b00000011, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b01000001, 0b11000010, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000111, 0b11110000, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b00001111, 0b11111000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00011100, 0b00111000, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b00011000, 0b00011100, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00011111, 0b00111000, 0b00001100, 0b01111100, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00111111, 0b00111000, 0b00001100, 0b11111100, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00111000, 0b00011100, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b00011100, 0b00011000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00011110, 0b01111000, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b00001111, 0b11110000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000011, 0b11000000, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b11100000, 0b00000011, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000001, 0b11000000, 0b00000011, 0b10000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000011, 0b10000000, 0b10000001, 0b11000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000011, 0b00000001, 0b10000000, 0b11000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b00000001, 0b10000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000001, 0b10000000, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b00000001, 0b10000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000001, 0b10000000, 0b00000000, 0b00000000, 0b00000000,
  0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000
};

const int BrightnessSymbol_width = 64;
const int BrightnessSymbol_height = 32;
const int BrightnessSymbol_size = 256;








class DisplayManager {
private:
    //Adafruit_SSD1306 display;
    U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2;
    //U8G2_SH1122_256X64_F_4W_HW_SPI u8g2;
    bool isInitialized = false;
    int brightness = 255;
    unsigned long lastDimStep = 0;
    unsigned long lastInput = 0;
    int targetBrightness = 255;

public:
    DisplayManager() : u8g2(U8G2_R0, U8X8_PIN_NONE) {}
    //DisplayManager() : u8g2(U8G2_R0, OLED_CS, OLED_DC, OLED_RST) {}
    //DisplayManager() : display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET) {}

    void setup(int pinSDA, int pinSCL) {

        //SPI.begin(SPI_CLK, SPI_MISO, SPI_MOSI, OLED_CS);
        Wire.begin(pinSDA, pinSCL);
        u8g2.begin();

        if(!u8g2.getBufferPtr()) {
            Serial.println(F("U8G2 SPI allocation failed"));
            return;
        }
        
        isInitialized = true;
        u8g2.clearBuffer();
        u8g2.setFont(u8g2_font_6x10_tf);
        u8g2.setDrawColor(1);
        u8g2.drawStr(20, 32, "Hello (:"); // x, y (baseline for text)
        u8g2.sendBuffer();
    }


    // ------------------ Refactored to here ------------------

    //------------------------------------------------------------------------
    
    /**
     *  leftHint = longPress
     *  rightHint = shortPress
     *  turnHint = rotation
     * 
     *  pass nullptr if hint shouldn't be visible
     */
    void drawNavHint(const char* leftHint, const char* rightHint, const char* turnHint) {
        u8g2.setDrawColor(1);
        if(leftHint) {
            // display.fillRoundRect(4, 57, 15, 6, 6, SSD1306_WHITE);
            // display.setTextSize(1);
            // display.setTextColor(SSD1306_WHITE);
            // display.setCursor(22, 57);
            // display.println(leftHint);
            u8g2.drawRBox(4, 57, 15, 6, 2); // x, y, w, h, r, color(1=filled)
            u8g2.drawStr(22, 57, leftHint);
        }
        if(rightHint) {
            u8g2.drawDisc(80, 60, 3, U8G2_DRAW_ALL);
            u8g2.drawStr(88, 57, rightHint);
            // display.fillCircle(80, 60, 3, SSD1306_WHITE);
            // display.setTextSize(1);
            // display.setTextColor(SSD1306_WHITE);
            // display.setCursor(88, 57);
            // display.println(rightHint);
        }
        if(turnHint) {
            u8g2.drawStr(45, 40, turnHint);
        }
    }

    void wakeUp() {
        lastInput = xTaskGetTickCount() * portTICK_PERIOD_MS;
        targetBrightness = 255;
        u8g2.setPowerSave(0);
        // display.ssd1306_command(SSD1306_SETPRECHARGE);
        // display.ssd1306_command(64);
    }

    void loop() {
        unsigned long timeNOW = xTaskGetTickCount() * portTICK_PERIOD_MS;
        int timeDifference = timeNOW - lastInput;


        if (timeDifference > 10000) {
            targetBrightness = 0;
            // display.ssd1306_command(SSD1306_SETPRECHARGE);
            // display.ssd1306_command(0);
        }


        if (brightness != targetBrightness && (timeNOW - lastDimStep) > 50) {
            lastDimStep = timeNOW;

            if (brightness < targetBrightness) {
                brightness += 20; // Fade-In
                if (brightness > targetBrightness) brightness = targetBrightness;
            } else {
                brightness -= 10; // Fade-Out
                if (brightness < targetBrightness) brightness = targetBrightness;
            }

            Serial.printf("Brightness is: %d\r\n", brightness);
            // display.ssd1306_command(SSD1306_SETCONTRAST);
            // display.ssd1306_command(brightness);
            u8g2.setContrast(brightness);
        }
    }

    void drawSelection(const char* lineBuffer) {
        //println(title)
        // display.setTextSize(1);
        // display.setCursor(0, 32);
        // display.println("<");
        // display.setCursor(120, 32);
        // display.println(">");
        // display.setTextSize(2);
        // display.setTextColor(SSD1306_WHITE);
        // int len = (128 - strlen(lineBuffer) * 12) / 2;
        // display.setCursor(len ,28);
        // display.println(lineBuffer);
        u8g2.setFont(u8g2_font_6x10_tf);
        u8g2.drawStr(0, 32, "<");
        u8g2.drawStr(120, 32, ">");
        
        u8g2.setFont(u8g2_font_ncenB08_tr); // Larger font
        u8g2.setDrawColor(1);
        int len = (128 - strlen(lineBuffer) * 7) / 2; // Adjusted for font width
        u8g2.drawStr(len, 38, lineBuffer);
    }


    void renderSliderScreen(const char* sliderName, int currentValue,int maxMap,  
                            int minVal, int maxVal, const char* leftHint, 
                            const char* rightHint, const char* turnHint)
    {
        // display.clearDisplay();
        // //display.drawBitmap(30, 0, BrightnessSymbol, 64, 32, SSD1306_WHITE);
        // drawSlider(currentValue, maxMap, minVal, maxVal);
        // drawNavHint(leftHint, rightHint, turnHint);
        // display.display();
        u8g2.clearBuffer();
        // u8g2.drawXBM(30, 0, BrightnessSymbol_width, BrightnessSymbol_height, BrightnessSymbol);
        drawSlider(currentValue, maxMap, minVal, maxVal);
        drawNavHint(leftHint, rightHint, turnHint);
        u8g2.sendBuffer();
    }

    void renderSelectionScreen(const char* lineBuffer, const char* leftHint, 
                            const char* rightHint, const char* turnHint)
    {
        // display.clearDisplay();
        // drawSelection(lineBuffer);
        // drawNavHint(leftHint, rightHint, turnHint);
        // display.display();
        u8g2.clearBuffer();
        drawSelection(lineBuffer);
        drawNavHint(leftHint, rightHint, turnHint);
        u8g2.sendBuffer();
    }

    void drawSlider(float currentValue,int maxMap, int minVal, int maxVal) {
            float percentage = (currentValue / (float)maxMap) * 100.0f;
            //int progress = map(currentValue, 0.0f, maxMap, 0, 100);
            int progress = (int)percentage;
            int ySlider = 29;
            int yText = 28;

            u8g2.setFont(u8g2_font_6x10_tf);
            u8g2.drawLine(0, ySlider, 100, ySlider); // horizontal line

            u8g2.setDrawColor(0);
            u8g2.drawDisc(progress, ySlider, 4, U8G2_DRAW_ALL); // filled
            u8g2.setDrawColor(1);
            u8g2.drawDisc(progress, ySlider, 3, U8G2_DRAW_ALL); // filled


            // display.drawLine(0, ySlider, 100, ySlider, SSD1306_WHITE);
            // display.fillCircle(progress,ySlider,4,SSD1306_BLACK);
            // display.fillCircle(progress,ySlider,3,SSD1306_WHITE);
            // display.setCursor(104, yText);
            // display.setTextSize(1);
            // display.printf("%d%%", progress);
            char buffer[8];
            snprintf(buffer, sizeof(buffer), "%d%%", progress);
            u8g2.drawStr(104, yText, buffer);
    }

    void renderStaticScreen(const char* text, const char* leftHint, const char* rightHint, const char* turnHint) {
        // display.clearDisplay();
        // int len = (128 - strlen(text) * 12) / 2;
        // display.setCursor(len ,28);
        // display.println(text);
        // drawNavHint(leftHint, rightHint, turnHint);
        // display.display();
        u8g2.clearBuffer();
        u8g2.setFont(u8g2_font_6x10_tf);
        int len = (128 - strlen(text) * 6) / 2;
        u8g2.drawStr(len, 28, text);
        drawNavHint(leftHint, rightHint, turnHint);
        u8g2.sendBuffer();
    }

    /*
    void animate() {
        int progress = 0;

        while (true) {
            delay(40);

            float norm = (float)progress / 100.0f; // normalize to 0..1
            float factor = 0.1f + 1.0f * norm * norm;
            int step = 1 + (int)(factor * 5);

            progress += step;

            display.clearDisplay();
            constrain(progress, 0, 100);
            int degree = map(progress,0, 100, 25, 300);

            int cx = 32;
            int cy = 32;
            int length = 25;

            float rad = degree * 3.14159 / 180.0;

            int x2 = cx + length * sin(rad);
            int y2 = cy - length * cos(rad);

            display.clearDisplay();
            display.drawLine(cx, cy, x2, y2, SSD1306_WHITE);
            display.drawCircle(32,32,27,SSD1306_WHITE);
            display.display();

            // // thick bar
            // display.fillRoundRect(5, 10, progress, 5, 3, SSD1306_WHITE);
            // // outer layer thick bar
            // display.drawRoundRect(3, 8, 102, 9, 3, SSD1306_WHITE);
            // display.setCursor(105, 9);
            // display.setTextSize(1);
            // display.printf("%d%%", progress);
            // // // line with dot
            // display.drawLine(0, 25, 100, 25, SSD1306_WHITE);
            // display.fillCircle(progress,25,4,SSD1306_BLACK);
            // display.fillCircle(progress,25,3,SSD1306_WHITE);
            // display.setCursor(105, 24);
            // display.setTextSize(1);
            // display.printf("%d%%", progress);


            // dots
            // for (int i = 0; i < 100; i += 7) {
            //     display.fillCircle(i + 5, 40, 2, SSD1306_WHITE);
            // }
            // display.fillRect(progress, 35, 128 - progress, 10, SSD1306_BLACK);

            // pills
            // for (int i = 0; i < 100; i += 15) {
            //     display.fillRoundRect(i , 50, 15, 6, 3, SSD1306_WHITE);
            // }
            // display.fillRect(progress, 50, 128 - progress, 10, SSD1306_BLACK);
            // // outer layer pills
            // for (int i = 0; i < 100; i += 15) {
            //     display.drawRoundRect(i - 1 , 50, 15, 6, 3, SSD1306_WHITE);
            // }

            // rectangle
            // for (int i = 0; i < 100; i++) {
            //     int y = map(i, 0, 100, 1, 32);
            //     display.fillRect(i, 64 - y, 1, y, SSD1306_WHITE);
            // }
            // display.fillRect(progress, 0, 128 - progress, 64, SSD1306_BLACK);
            display.display();



            //progress++;

            if (progress > 100) {
                progress = 0;
            }
        }
    }

    */

    /*
    void plotCurve() {
        display.clearDisplay();

        // OLED is 128x64
        // We'll use:
        // X = 0 → 127
        // Y = 63 → 0 (screen is inverted vertically)

        for (int x = 0; x < 128; x++) {
            // Map screen x to opacity 0..255
            int opacity = map(x, 0, 127, 1, 255);

            // Same formula as your brightness code
            float norm = (float)opacity / 255.0f;
            float factor = 0.1f + 3.0f * norm * norm;
            int step = 1 + (int)(factor * 20);

            // step is roughly 3..33
            // Map step to screen height
            int y = map(step, 1, 35, 63, 0);

            display.drawPixel(x, y, SSD1306_WHITE);
        }

        // Optional axes
        display.drawLine(0, 63, 127, 63, SSD1306_WHITE); // X axis
        display.drawLine(0, 0, 0, 63, SSD1306_WHITE);    // Y axis

        display.display();
    }

    */
};
